extends: default

rules:
  comments:
    min-spaces-from-content: 1
  document-start:
    present: false
  empty-lines:
    max: 1
  line-length:
    max: 135
  new-lines:
    type: platform
  truthy:
    check-keys: false

ignore: |
  artifacts/
