filetype on
filetype indent on
filetype plugin on

set hlsearch
set ignorecase
set incsearch
set number
set showmode
set smartcase

syntax on

set directory=$XDG_CONFIG_HOME/vim/.swap,~/AppData/Local/Temp,c:/tmp,c:/temp
set backupdir=$XDG_CONFIG_HOME/vim/.backup,~/AppData/Local/Temp,c:/tmp,c:/temp
set undodir=$XDG_CONFIG_HOME/vim/.undo
set viminfo+=n$XDG_CONFIG_HOME/vim/viminfo
