set nocompatible
set termguicolors

set directory=$XDG_CONFIG_HOME/vim/.swap,~/AppData/Local/Temp,c:/tmp,c:/temp
set backupdir=$XDG_CONFIG_HOME/vim/.backup,~/AppData/Local/Temp,c:/tmp,c:/temp
set undodir=$XDG_CONFIG_HOME/vim/.undo
set viminfo+=n$XDG_CONFIG_HOME/vim/viminfo

call plug#begin()
Plug 'catppuccin/vim', { 'as': 'catppuccin' }
Plug 'vim-airline/vim-airline'
Plug 'SirVer/ultisnips'
call plug#end()

colorscheme catppuccin_mocha

filetype on
filetype indent on
filetype plugin on

set autoindent
set hlsearch
set ignorecase
set incsearch
set noshowmode
set number
set showcmd
set smartcase
set wildmenu

" Disable audible and visual bells.
set visualbell
set t_vb=

syntax on

let g:UltiSnipsSnippetsDir=expand('~/.config/vim/UltiSnips')
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
