User:
  CARGO_HOME: '%DEV_HOME%/.cargo'
  DEV_HOME: D:/Users/lancra
  DEVUSERPROFILE: D:\Users\lancra
  GOPATH: '%DEVUSERPROFILE%\go'
  HOME: C:/Users/lancra
  NPM_CONFIG_CACHE: '%DEVUSERPROFILE%\AppData\Local\npm-cache'
  NUGET_PACKAGES: '%DEVUSERPROFILE%\.nuget\packages'
  ONEDRIVE: '%USERPROFILE%\OneDrive'
  ONEDRIVECONSUMER: '%USERPROFILE%\OneDrive'
  PATH:
  - '%LOCALAPPDATA%\Microsoft\WindowsApps'
  - '%LOCALAPPDATA%\Microsoft\WinGet\Links'
  - '%USERPROFILE%\bin'
  - '%LOCALAPPDATA%\Programs\oh-my-posh\bin'
  - '%LOCALAPPDATA%\Programs\Microsoft VS Code\bin'
  - '%LOCALAPPDATA%\Programs\Azure Data Studio\bin'
  - '%LOCALAPPDATA%\Programs\KDiff3\bin'
  - '%DEVUSERPROFILE%\.cargo\bin'
  - '%USERPROFILE%\.dotnet\tools'
  - '%DEVUSERPROFILE%\go\bin'
  - '%APPDATA%\npm'
  - '%LOCALAPPDATA%\Programs\Python\Python312\Scripts\'
  - '%LOCALAPPDATA%\Programs\Python\Python312\'
  - '%LOCALAPPDATA%\Programs\Python\Launcher\'
  PIP_CACHE_DIR: '%DEVUSERPROFILE%\AppData\Local\pip\Cache'
  POSH_INSTALLER: winget
  POSH_THEMES_PATH: '%LOCALAPPDATA%\Programs\oh-my-posh\themes'
  RIPGREP_CONFIG_PATH: '%XDG_CONFIG_HOME%/ripgrep/config'
  XDG_CONFIG_HOME: '%HOME%/.config'
Machine:
  PATH:
  - '%SYSTEMROOT%'
  - '%SYSTEMROOT%\System32'
  - '%SYSTEMROOT%\System32\OpenSSH'
  - '%SYSTEMROOT%\System32\Wbem'
  - '%SYSTEMROOT%\System32\WindowsPowerShell\v1.0'
  - '%PROGRAMFILES%\PowerShell\7'
  - '%PROGRAMFILES(X86)%\Windows Kits\10\Windows Performance Toolkit'
  - '%PROGRAMFILES(X86)%\NVIDIA Corporation\PhysX\Common'
  - '%PROGRAMFILES%\NVIDIA Corporation\NVIDIA NvDLISR'
  - '%PROGRAMFILES%\gsudo\Current'
  - '%PROGRAMFILES%\Vim\vim91'
  - '%PROGRAMFILES%\Git\cmd'
  - '%PROGRAMFILES%\Git\usr\bin'
  - '%PROGRAMFILES(X86)%\gnupg\bin'
  - '%PROGRAMFILES(X86)%\Gpg4win\..\GnuPG\bin'
  - '%PROGRAMFILES%\Meld'
  - '%PROGRAMFILES%\GitHub CLI'
  - '%PROGRAMFILES%\nu\bin'
  - '%PROGRAMFILES%\Microsoft SDKs\Azure\CLI2\wbin'
  - '%PROGRAMFILES%\dotnet'
  - '%PROGRAMFILES(X86)%\dotnet-core-uninstall'
  - '%PROGRAMFILES%\SqlCmd'
  - '%PROGRAMFILES%\Microsoft SQL Server\160\Tools\Binn'
  - '%PROGRAMFILES%\Microsoft SQL Server\150\Tools\Binn'
  - '%PROGRAMFILES%\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn'
  - '%PROGRAMFILES%\Go\bin'
  - '%PROGRAMFILES%\nodejs'
  - '%PROGRAMFILES%\PuTTY'
  - '%PROGRAMFILES%\Calibre2'

