[v1]
"cargo-audit 0.20.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-audit.exe"]
"cargo-expand 1.0.79 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand.exe"]
"cargo-update 13.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update-config.exe",
    "cargo-install-update.exe",
]
"cargo-watch 8.5.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch.exe"]
"rustlings 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rustlings.exe"]
"taplo-cli 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["taplo.exe"]
"typos-cli 1.19.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["typos.exe"]
